// Generated by llvm2cpp - DO NOT MODIFY!

#include <llvm/Pass.h>
#include <llvm/PassManager.h>
#include <llvm/ADT/SmallVector.h>
#include <llvm/Analysis/Verifier.h>
#include <llvm/IR/BasicBlock.h>
#include <llvm/IR/CallingConv.h>
#include <llvm/IR/Constants.h>
#include <llvm/IR/DerivedTypes.h>
#include <llvm/IR/Function.h>
#include <llvm/IR/GlobalVariable.h>
#include <llvm/IR/IRPrintingPasses.h>
#include <llvm/IR/InlineAsm.h>
#include <llvm/IR/Instructions.h>
#include <llvm/IR/LLVMContext.h>
#include <llvm/IR/Module.h>
#include <llvm/Support/FormattedStream.h>
#include <llvm/Support/MathExtras.h>
#include <algorithm>
using namespace llvm;

Module* makeLLVMModule();

int main(int argc, char**argv) {
  Module* Mod = makeLLVMModule();
  verifyModule(*Mod, PrintMessageAction);
  PassManager PM;
  PM.add(createPrintModulePass(&outs()));
  PM.run(*Mod);
  return 0;
}


Module* makeLLVMModule() {
 // Module Construction
 Module* mod = new Module("a.ll", getGlobalContext());
 mod->setDataLayout("0x3448ca0");
 mod->setTargetTriple("x86_64-unknown-linux-gnu");
 
 // Type Definitions
 std::vector<Type*>FuncTy_0_args;
 FunctionType* FuncTy_0 = FunctionType::get(
  /*Result=*/IntegerType::get(mod->getContext(), 32),
  /*Params=*/FuncTy_0_args,
  /*isVarArg=*/false);
 
 PointerType* PointerTy_1 = PointerType::get(IntegerType::get(mod->getContext(), 32), 0);
 
 ArrayType* ArrayTy_3 = ArrayType::get(IntegerType::get(mod->getContext(), 32), 10);
 
 PointerType* PointerTy_2 = PointerType::get(ArrayTy_3, 0);
 
 ArrayType* ArrayTy_5 = ArrayType::get(IntegerType::get(mod->getContext(), 32), 4);
 
 PointerType* PointerTy_4 = PointerType::get(ArrayTy_5, 0);
 
 
 // Function Declarations
 
 Function* func_main = mod->getFunction("main");
 if (!func_main) {
 func_main = Function::Create(
  /*Type=*/FuncTy_0,
  /*Linkage=*/GlobalValue::ExternalLinkage,
  /*Name=*/"main", mod); 
 func_main->setCallingConv(CallingConv::C);
 }
 AttributeSet func_main_PAL;
 {
  SmallVector<AttributeSet, 4> Attrs;
  AttributeSet PAS;
   {
    AttrBuilder B;
    B.addAttribute(Attribute::NoUnwind);
    B.addAttribute(Attribute::UWTable);
    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
   }
  
  Attrs.push_back(PAS);
  func_main_PAL = AttributeSet::get(mod->getContext(), Attrs);
  
 }
 func_main->setAttributes(func_main_PAL);
 
 // Global Variable Declarations

 
 // Constant Definitions
 ConstantInt* const_int32_6 = ConstantInt::get(mod->getContext(), APInt(32, StringRef("1"), 10));
 ConstantInt* const_int32_7 = ConstantInt::get(mod->getContext(), APInt(32, StringRef("0"), 10));
 
 // Global Variable Definitions
 
 // Function Definitions
 
 // Function: main (func_main)
 {
  
  BasicBlock* label_entry = BasicBlock::Create(mod->getContext(), "entry",func_main,0);
  
  // Block entry (label_entry)
  AllocaInst* ptr_retval = new AllocaInst(IntegerType::get(mod->getContext(), 32), "retval", label_entry);
  ptr_retval->setAlignment(4);
  AllocaInst* ptr_a = new AllocaInst(ArrayTy_3, "a", label_entry);
  ptr_a->setAlignment(16);
  AllocaInst* ptr_b = new AllocaInst(ArrayTy_5, "b", label_entry);
  ptr_b->setAlignment(16);
  AllocaInst* ptr_c = new AllocaInst(IntegerType::get(mod->getContext(), 32), "c", label_entry);
  ptr_c->setAlignment(4);
  StoreInst* void_8 = new StoreInst(const_int32_7, ptr_retval, false, label_entry);
  StoreInst* void_9 = new StoreInst(const_int32_7, ptr_c, false, label_entry);
  void_9->setAlignment(4);
  LoadInst* int32_10 = new LoadInst(ptr_c, "", false, label_entry);
  int32_10->setAlignment(4);
  BinaryOperator* int32_add = BinaryOperator::Create(Instruction::Add, int32_10, const_int32_6, "add", label_entry);
  CastInst* int64_idxprom = new SExtInst(int32_add, IntegerType::get(mod->getContext(), 64), "idxprom", label_entry);
  std::vector<Value*> ptr_arrayidx_indices;
  ptr_arrayidx_indices.push_back(const_int32_7);
  ptr_arrayidx_indices.push_back(int64_idxprom);
  Instruction* ptr_arrayidx = GetElementPtrInst::Create(ptr_b, ptr_arrayidx_indices, "arrayidx", label_entry);
  LoadInst* int32_11 = new LoadInst(ptr_arrayidx, "", false, label_entry);
  int32_11->setAlignment(4);
  LoadInst* int32_12 = new LoadInst(ptr_c, "", false, label_entry);
  int32_12->setAlignment(4);
  CastInst* int64_idxprom1 = new SExtInst(int32_12, IntegerType::get(mod->getContext(), 64), "idxprom1", label_entry);
  std::vector<Value*> ptr_arrayidx2_indices;
  ptr_arrayidx2_indices.push_back(const_int32_7);
  ptr_arrayidx2_indices.push_back(int64_idxprom1);
  Instruction* ptr_arrayidx2 = GetElementPtrInst::Create(ptr_a, ptr_arrayidx2_indices, "arrayidx2", label_entry);
  StoreInst* void_13 = new StoreInst(int32_11, ptr_arrayidx2, false, label_entry);
  void_13->setAlignment(4);
  ReturnInst::Create(mod->getContext(), const_int32_7, label_entry);
  
 }
 
 return mod;
}
